development:
  adapter: postgresql
  encoding: unicode
  database: local_tassjel_db
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: tassjel_prod
  pool: 5
  username: 
  password: 