development:
  adapter: postgresql
  encoding: SQL_ASCII
  database: local_tassjel_db
  pool: 5
  username: 
  password: 

production:
  adapter: postgresql
  encoding: SQL_ASCII
  database: tassjel_prod
  pool: 5
  username: 
  password: 